Add "current" option to census year selection
vanderbilt-redcap/Census-Tract-Geocoding-External-Module pull request #1
Opened 2024-06-05 18:50 UTC by ChemiKyle

This change is motivated by a request to add 2023 as an option, however the `Census2023_Current` is not in the API's domain for the `vintage` param:

https://github.com/vanderbilt-redcap/Census-Tract-Geocoding-External-Module/blob/40d7d912d3da6a7396471aa55a4cbb8a457e5ff9/CensusExternalModule.php#L76

Adding this "current" option was lower hanging fruit than fetching the domain and/or mapping years to valid `benchmark` and `vintage` inputs (let alone the effort of understanding government acronyms).

2024-06-05 18:51 UTC, ChemiKyle commented
@mmcev106 I wasn't able to add you as a reviewer so I'm pinging you here.

2024-06-05 21:15 UTC, mmcev106 requested changes

2024-06-05 22:31 UTC, ChemiKyle commented on config.json
> +						{ "value": "current", "name": "Current" },
I used the same website, there are at least 3 different combinations that could be interpreted as "2023 data", so I made this PR in lieu of differentiating them because it seems useful _in addition_ to being able to specify 2023 data.  
"Current_Current" is one of the values that evaluates to the current year and is [always expected to be the latest data](https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.pdf). I couldn't find anything from census.gov regarding the returned data's schema changing between versions (the 2 examples they provide are identical), but the data itself changing when you make the call is the intent of the "current" option.

---

I tested with a few different (TigerWeb) keys, I don't get any errors with `current` or `2020`; however there are some tangential issues that are independent of this PR (i.e. they show up in the `main` branch with 2020 selected as the census year):
- if the `$addressField` is a "Notes Box" type, jQuery's `change` function doesn't fire
- Some values aren't processed populate despite being present in the API response (i.e. `ZIP`)

---

Regarding 2023 data specifically, this PR is a patch job while I try to figure out what the difference is among the different benchmarks and vintages where 2023 data exists, since it differs from how you designed the 2020 and 2010 pulls. It has the added benefit of always allowing the latest data so there shouldn't be any further dev time required if somebody wants the newest data whenever it's released.

<details>
<summary>Weedy details on different params</summary>
your extant options are under the `benchmark = Public_AR_Current` and `vintage = Census<YYYY>_Current`, 2023 specific data is under that same benchmark option with `vintage = ACS2023_Current`
`benchmark = Public_AR_ACS2023`
</details>

2024-06-06 18:07 UTC, ChemiKyle commented on config.json
> +						{ "value": "current", "name": "Current" },
Replaced this with a warning not to implement it at all

2024-06-06 20:50 UTC, mmcev106 approved these changes
Approved.  You may want to know that it looks like there is a tabs vs. spaces discrepancy, but those are pretty low on my priority list to enforce personally.

2024-06-07 15:59 UTC, merged