Feature/allow benchmark and vintage selection
vanderbilt-redcap/Census-Tract-Geocoding-External-Module pull request #7
Opened 2024-10-25 23:54 UTC by ChemiKyle

This constitutes a major version change (although it does still work with the previous version).

Due to recent breakages with API parameters, rather than selecting a census year, users must select a benchmark and vintage from which to receive data. The module will now dynamically fetch currently available benchmark/vintage pairs from the US Census API.

Closes #3  
Due to the `Census Blocks` geographic bound not appearing in some vintages (some of them prepend the year), desired fields are searched for in sequentially increasing geographic areas (default ordering is by land area, based on the - possibly dubious - assumption that people live on land).

QoL:
- Moved all the javascript into its own file
- Bumped framework version up to 16

2024-10-28 16:00 UTC, mmcev106 requested changes
@ChemiKyle, this looks great overall.  Apart from my comment, the only other concern is around you mentioning that updating the major version would be appropriate, even though old versions would still work.  Would you be able to clarify?  My main concern is to avoid project configuration changes if at all possible, as that will end up being more work for you.

2024-10-28 16:00 UTC, mmcev106 commented on CensusExternalModule.php
> +		echo "<script> const module = " . $this->getJavascriptModuleObjectName() . "</script>";
Defining anything in JS top level scope is discouraged in module development.  This one I think is especially concerning as `module` is very generic and can easily conflict with other modules.  There are a few different ways to do this safely.  If you'd like to discuss those, or if it isn't clear why this is something we should always consider during development, please give me call.

2024-10-28 17:40 UTC, ChemiKyle commented on CensusExternalModule.php
> +		echo "<script> const module = " . $this->getJavascriptModuleObjectName() . "</script>";
Good catch, that wasn't meant to make it into the commit! No discussion needed, I'm well aware of the collision potential there.  
Quick sanity check, setting `const module = <JSMOName>` in the anonymous function used in `$(document).ready( () => {} )` is safely confined within the scope of that function, right?  
https://github.com/vanderbilt-redcap/Census-Tract-Geocoding-External-Module/pull/7/files#diff-431e5adb210d9982cdf7bacdacad1bab1cd70c57028cb41316d8bb79d2d8b046R4

2024-10-28 17:49 UTC, ChemiKyle commented
Regarding major version change: my reasoning is that I'm deprecating an option in the configuration settings, replacing it with a new option. While I've added logic to process extant values for the deprecated option, the new pathway is preferred in the logic and I don't intend to maintain the logic for the deprecated option.  
Since the old option is setting parameters for an API which has regular flux, the processing of those options will _eventually_ break.

2024-10-28 17:52 UTC, mmcev106 commented
What is the transition plan for projects that use this module?

2024-10-28 19:15 UTC, ChemiKyle commented
The easiest for them would be for me to add logic to transition them to a benchmark/vintage that equates to their `year` option. I considered doing this pre-emptively with an adjustment to the `transitionOldSettings` function but left it out since I didn't want to disrupt my ability to test the old path. I can add that back, now that I'm not entrenched in the problem I realize the solution is rather trivial.  
The easiest path for me is that they notice when failures begin to occur and select a benchmark/vintage that meets their needs.

2024-10-29 15:17 UTC, mmcev106 commented
@ChemiKyle, I believe projects that use this are configured with hard census data that won't change (2010 or 2020).  Can you confirm that those projects will continue functioning as expected with no changes needed?

2024-10-29 16:11 UTC, ChemiKyle commented
Yes, if the new `benchmark_vintage` configuration is not set, the `year` will be processed as usual, that's handled by these lines:

https://github.com/vanderbilt-redcap/Census-Tract-Geocoding-External-Module/pull/7/files#diff-1cff3038c55e93ba1f53e6ac162b35d0d148b0f86eb260b1fabc9bf8118f3934R9-R13

https://github.com/vanderbilt-redcap/Census-Tract-Geocoding-External-Module/pull/7/files#diff-0ccc8949cebe86f8816a2a07dd72559334b4718cc7883f8bbf12a0d89240c200R8-R12

2024-10-29 16:59 UTC, mmcev106 approved these changes
That all sounds good to me.  Approved!

2024-10-31 21:20 UTC, merged